-- Deep Signal cache table — stores the LLM-generated narrative + outreach
-- scripts for each investigated parcel. Cache key is (pin). One row per parcel.
--
-- Generated by POST /api/deep-signal/{pin}. Call is idempotent once cached —
-- repeat clicks return the stored row instantly with no Claude API cost.
--
-- Invalidation: manually delete the row to force regeneration (e.g. after
-- new investigation signals land). There is no auto-invalidation today.

CREATE TABLE IF NOT EXISTS deep_signals_v3 (
    pin              TEXT PRIMARY KEY,
    zip_code         TEXT,
    report           JSONB,                -- full raw LLM response
    motivation       TEXT,                 -- 3-5 sentence psychological read
    timeline         TEXT,                 -- "0-3 months" | "3-6 months" | "6-12 months" | "12+ months"
    best_channel     TEXT,                 -- "call" | "mail" | "door"
    call_script      TEXT,                 -- 4-6 sentence phone script
    mail_script      TEXT,                 -- 4-6 sentence letter
    door_script      TEXT,                 -- 4-6 sentence door knock
    what_not_to_say  TEXT,                 -- 2-3 specific avoids, tied to research
    model            TEXT,                 -- e.g. 'claude-sonnet-4-20250514'
    tokens_in        INTEGER,
    tokens_out       INTEGER,
    generated_at     TIMESTAMPTZ DEFAULT NOW(),
    updated_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_deep_signals_v3_zip
    ON deep_signals_v3(zip_code);

-- For "most recently generated across the whole system" admin queries
CREATE INDEX IF NOT EXISTS idx_deep_signals_v3_generated_at
    ON deep_signals_v3(generated_at DESC);

-- Update `updated_at` automatically on row change
CREATE OR REPLACE FUNCTION deep_signals_v3_touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS deep_signals_v3_touch_updated_at ON deep_signals_v3;
CREATE TRIGGER deep_signals_v3_touch_updated_at
BEFORE UPDATE ON deep_signals_v3
FOR EACH ROW
EXECUTE FUNCTION deep_signals_v3_touch_updated_at();
